# Imports

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from seaborn import countplot
from matplotlib.pyplot import figure, show
from scipy import stats
from sklearn.preprocessing import StandardScaler
import warnings
import gc
from sklearn import preprocessing
warnings.filterwarnings('ignore')

#warnings.filterwarnings('default')

# Load Data

In [2]:
df = pd.read_csv('/Volumes/C/Thesis-2019/cluster-output/balanced_DG_out.csv', sep=';')

# EDA

In [3]:
#pd.options.display.float_format = '{:20,.8f}'.format
#df = df.drop(['tx_hash','in_btc','out_btc','in_malicious','out_malicious','is_malicious', 'all_malicious'], axis=1)
print(df['out_and_tx_malicious'].value_counts())
df.describe()

0    30248026
1       57471
Name: out_and_tx_malicious, dtype: int64

,indegree,outdegree,total_btc,mean_in_btc,mean_out_btc,out_and_tx_malicious
count,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07
mean,2.170776e+00,2.148168e+00,1.193349e+02,5.092511e+01,3.128752e+01,1.896389e-03
std,7.632696e+00,4.507831e+00,2.650145e+03,9.808164e+02,7.254951e+02,4.350623e-02
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,1.000000e+00,2.000000e+00,2.069200e-01,6.419830e-02,5.050000e-02,0.000000e+00
50%,1.000000e+00,2.000000e+00,1.975022e+00,5.379369e-01,4.927500e-01,0.000000e+00
75%,2.000000e+00,2.000000e+00,1.861750e+01,5.690627e+00,4.574000e+00,0.000000e+00
max,1.932000e+03,1.322000e+03,1.050000e+06,4.992596e+05,5.000000e+05,1.000000e+00

In [4]:
scaled_df = df.copy()

In [5]:
#scaled_df.hist(figsize=(20, 20), bins=50, xlabelsize=8, ylabelsize=8, log=True);
#scaled_df.describe()

In [6]:
scaled_df['indegree'] = np.log(scaled_df['indegree']).replace(0, 0.1).replace(-np.inf, 0)
scaled_df['outdegree']= np.log(scaled_df['outdegree']).replace(0, 0.1).replace(-np.inf, 0)
# # #df['in_btc'] = np.log(df['in_btc']).replace(-np.inf, 0)
# # #df['out_btc']= np.log(df['out_btc']).replace(-np.inf, 0)
scaled_df['total_btc']= np.log(scaled_df['total_btc']).replace(0, 0.1).replace(-np.inf, 0)
scaled_df['mean_in_btc']= np.log(scaled_df['mean_in_btc']).replace(0, 0.1).replace(-np.inf, 0)
scaled_df['mean_out_btc']= np.log(scaled_df['mean_out_btc']).replace(0, 0.1).replace(-np.inf, 0)

scaled_df.describe()

,indegree,outdegree,total_btc,mean_in_btc,mean_out_btc,out_and_tx_malicious
count,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07
mean,4.553126e-01,6.540308e-01,6.796926e-01,-4.125428e-01,-6.660264e-01,1.896389e-03
std,5.980675e-01,3.316137e-01,2.867677e+00,2.901628e+00,2.880976e+00,4.350623e-02
min,0.000000e+00,-9.170134e+00,-1.842068e+01,-1.842068e+01,-1.842068e+01,0.000000e+00
25%,1.000000e-01,6.931472e-01,-1.575423e+00,-2.644624e+00,-2.912204e+00,0.000000e+00
50%,1.000000e-01,6.931472e-01,6.805794e-01,-5.293025e-01,-6.936473e-01,0.000000e+00
75%,6.931472e-01,6.931472e-01,2.924102e+00,1.738820e+00,1.520388e+00,0.000000e+00
max,7.566311e+00,7.186901e+00,1.386430e+01,1.312088e+01,1.312236e+01,1.000000e+00

In [7]:
norm_scaled_df = scaled_df.copy()
norm_scaled_df['indegree'] = preprocessing.Normalizer(norm='l1').fit_transform(norm_scaled_df['indegree'].values.reshape(-1, 1))
norm_scaled_df['outdegree'] = preprocessing.Normalizer(norm='l1').fit_transform(norm_scaled_df['outdegree'].values.reshape(-1, 1))
#scaled_df['in_btc'] = preprocessing.Normalizer().fit_transform(df['in_btc'].values.reshape(-1, 1))
#scaled_df['out_btc'] = preprocessing.Normalizer().fit_transform(df['out_btc'].values.reshape(-1, 1))
norm_scaled_df['total_btc'] = preprocessing.Normalizer(norm='l1').fit_transform(norm_scaled_df['total_btc'].values.reshape(-1, 1))
norm_scaled_df['mean_in_btc'] = preprocessing.Normalizer(norm='l1').fit_transform(norm_scaled_df['mean_in_btc'].values.reshape(-1, 1))
norm_scaled_df['mean_out_btc'] = preprocessing.Normalizer(norm='l1').fit_transform(norm_scaled_df['mean_out_btc'].values.reshape(-1, 1))
norm_scaled_df.describe()

,indegree,outdegree,total_btc,mean_in_btc,mean_out_btc,out_and_tx_malicious
count,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07
mean,9.904386e-01,9.938749e-01,1.808887e-01,-1.237021e-01,-1.771629e-01,1.896389e-03
std,9.731383e-02,7.831188e-02,9.835036e-01,9.874899e-01,9.810875e-01,4.350623e-02
min,0.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00
25%,1.000000e+00,1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00
50%,1.000000e+00,1.000000e+00,1.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00
75%,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00
max,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [8]:
mx_scaled_df = scaled_df.copy()
mx_scaled_df['indegree'] = preprocessing.MinMaxScaler(feature_range=(-1, 1)).fit_transform(mx_scaled_df['indegree'].values.reshape(-1, 1))
mx_scaled_df['outdegree'] = preprocessing.MinMaxScaler(feature_range=(-1, 1)).fit_transform(mx_scaled_df['outdegree'].values.reshape(-1, 1))
#scaled_df['in_btc'] = StandardScaler().fit_transform(df['in_btc'].values.reshape(-1, 1))
#scaled_df['out_btc'] = StandardScaler().fit_transform(df['out_btc'].values.reshape(-1, 1))
mx_scaled_df['total_btc'] = preprocessing.MinMaxScaler(feature_range=(-1, 1)).fit_transform(mx_scaled_df['total_btc'].values.reshape(-1, 1))
mx_scaled_df['mean_in_btc'] = preprocessing.MinMaxScaler(feature_range=(-1, 1)).fit_transform(mx_scaled_df['mean_in_btc'].values.reshape(-1, 1))
mx_scaled_df['mean_out_btc'] = preprocessing.MinMaxScaler(feature_range=(-1, 1)).fit_transform(mx_scaled_df['mean_out_btc'].values.reshape(-1, 1))
mx_scaled_df.describe()

,indegree,outdegree,total_btc,mean_in_btc,mean_out_btc,out_and_tx_malicious
count,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07
mean,-8.796474e-01,2.012158e-01,1.832358e-01,1.418672e-01,1.257413e-01,1.896389e-03
std,1.580869e-01,4.054692e-02,1.776477e-01,1.839876e-01,1.826695e-01,4.350623e-02
min,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,-1.000000e+00,0.000000e+00
25%,-9.735670e-01,2.059987e-01,4.353523e-02,3.345387e-04,-1.667848e-02,0.000000e+00
50%,-9.735670e-01,2.059987e-01,1.832908e-01,1.344637e-01,1.239900e-01,0.000000e+00
75%,-8.167807e-01,2.059987e-01,3.222732e-01,2.782817e-01,2.643719e-01,0.000000e+00
max,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00

In [9]:
rb_scaled_df = scaled_df.copy()
rb_scaled_df['indegree'] = preprocessing.RobustScaler(quantile_range=(25.0, 75.0), with_centering=True,
       with_scaling=True).fit_transform(rb_scaled_df['indegree'].values.reshape(-1, 1))

rb_scaled_df['outdegree'] = preprocessing.RobustScaler(quantile_range=(25.0, 75.0), with_centering=True,
       with_scaling=True).fit_transform(rb_scaled_df['outdegree'].values.reshape(-1, 1))

#scaled_df['in_btc'] = StandardScaler().fit_transform(df['in_btc'].values.reshape(-1, 1))
#scaled_df['out_btc'] = StandardScaler().fit_transform(df['out_btc'].values.reshape(-1, 1))

rb_scaled_df['total_btc'] = preprocessing.RobustScaler(quantile_range=(25.0, 75.0), with_centering=True,
       with_scaling=True).fit_transform(rb_scaled_df['total_btc'].values.reshape(-1, 1))

rb_scaled_df['mean_in_btc'] = preprocessing.RobustScaler(quantile_range=(25.0, 75.0), with_centering=True,
       with_scaling=True).fit_transform(rb_scaled_df['mean_in_btc'].values.reshape(-1, 1))

rb_scaled_df['mean_out_btc'] = preprocessing.RobustScaler(quantile_range=(25.0, 75.0), with_centering=True,
       with_scaling=True).fit_transform(rb_scaled_df['mean_out_btc'].values.reshape(-1, 1))

rb_scaled_df.describe()

,indegree,outdegree,total_btc,mean_in_btc,mean_out_btc,out_and_tx_malicious
count,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07
mean,5.990294e-01,-3.911640e-02,-1.970901e-04,2.663651e-02,6.231312e-03,1.896389e-03
std,1.008295e+00,3.316137e-01,6.373288e-01,6.619517e-01,6.499529e-01,4.350623e-02
min,-1.685922e-01,-9.863281e+00,-4.245173e+00,-4.081580e+00,-3.999248e+00,0.000000e+00
25%,0.000000e+00,0.000000e+00,-5.013868e-01,-4.825706e-01,-5.005100e-01,0.000000e+00
50%,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
75%,1.000000e+00,0.000000e+00,4.986132e-01,5.174294e-01,4.994900e-01,0.000000e+00
max,1.258762e+01,6.493754e+00,2.930025e+00,3.114032e+00,3.116915e+00,1.000000e+00

In [10]:
pw_scaled_df = scaled_df.copy()
pw_scaled_df['indegree'] = preprocessing.PowerTransformer().fit_transform(pw_scaled_df['indegree'].values.reshape(-1, 1))
pw_scaled_df['outdegree'] = preprocessing.PowerTransformer().fit_transform(pw_scaled_df['outdegree'].values.reshape(-1, 1))
#scaled_df['in_btc'] = StandardScaler().fit_transform(df['in_btc'].values.reshape(-1, 1))
#scaled_df['out_btc'] = StandardScaler().fit_transform(df['out_btc'].values.reshape(-1, 1))
pw_scaled_df['total_btc'] = preprocessing.PowerTransformer().fit_transform(pw_scaled_df['total_btc'].values.reshape(-1, 1))
pw_scaled_df['mean_in_btc'] = preprocessing.PowerTransformer().fit_transform(pw_scaled_df['mean_in_btc'].values.reshape(-1, 1))
pw_scaled_df['mean_out_btc'] = preprocessing.PowerTransformer().fit_transform(pw_scaled_df['mean_out_btc'].values.reshape(-1, 1))
pw_scaled_df.describe()

,indegree,outdegree,total_btc,mean_in_btc,mean_out_btc,out_and_tx_malicious
count,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07
mean,4.738478e-14,-3.183086e-15,-9.936649e-16,-4.971653e-16,-2.027804e-15,1.896389e-03
std,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,4.350623e-02
min,-1.559877e+00,-2.148662e+02,-7.097790e+00,-6.782302e+00,-6.300259e+00,0.000000e+00
25%,-7.266384e-01,2.095901e-01,-7.797216e-01,-7.634719e-01,-7.782930e-01,0.000000e+00
50%,-7.266384e-01,2.095901e-01,2.010590e-02,-7.655659e-03,-1.224934e-03,0.000000e+00
75%,1.110138e+00,2.095901e-01,7.866201e-01,7.554948e-01,7.624451e-01,0.000000e+00
max,1.808490e+00,9.594521e+00,4.401767e+00,4.307899e+00,4.681172e+00,1.000000e+00

In [11]:
# scaled_df['indegree'] = preprocessing.QuantileTransformer(output_distribution='uniform').fit_transform(scaled_df['indegree'].values.reshape(-1, 1))
# scaled_df['outdegree'] = preprocessing.QuantileTransformer(output_distribution='uniform').fit_transform(scaled_df['outdegree'].values.reshape(-1, 1))
# #scaled_df['in_btc'] = StandardScaler().fit_transform(df['in_btc'].values.reshape(-1, 1))
# #scaled_df['out_btc'] = StandardScaler().fit_transform(df['out_btc'].values.reshape(-1, 1))
# scaled_df['total_btc'] = preprocessing.QuantileTransformer(output_distribution='uniform').fit_transform(scaled_df['total_btc'].values.reshape(-1, 1))
# scaled_df['mean_in_btc'] = preprocessing.QuantileTransformer(output_distribution='uniform').fit_transform(scaled_df['mean_in_btc'].values.reshape(-1, 1))
# scaled_df['mean_out_btc'] = preprocessing.QuantileTransformer(output_distribution='uniform').fit_transform(scaled_df['mean_out_btc'].values.reshape(-1, 1))
# scaled_df.describe()

In [12]:
qt_scaled_df = scaled_df.copy()
qt_scaled_df['indegree'] = preprocessing.QuantileTransformer(output_distribution='normal').fit_transform(qt_scaled_df['indegree'].values.reshape(-1, 1))
qt_scaled_df['outdegree'] = preprocessing.QuantileTransformer(output_distribution='normal').fit_transform(qt_scaled_df['outdegree'].values.reshape(-1, 1))
#scaled_df['in_btc'] = StandardScaler().fit_transform(df['in_btc'].values.reshape(-1, 1))
#scaled_df['out_btc'] = StandardScaler().fit_transform(df['out_btc'].values.reshape(-1, 1))
qt_scaled_df['total_btc'] = preprocessing.QuantileTransformer(output_distribution='normal').fit_transform(qt_scaled_df['total_btc'].values.reshape(-1, 1))
qt_scaled_df['mean_in_btc'] = preprocessing.QuantileTransformer(output_distribution='normal').fit_transform(qt_scaled_df['mean_in_btc'].values.reshape(-1, 1))
qt_scaled_df['mean_out_btc'] = preprocessing.QuantileTransformer(output_distribution='normal').fit_transform(qt_scaled_df['mean_out_btc'].values.reshape(-1, 1))
qt_scaled_df.describe()

,indegree,outdegree,total_btc,mean_in_btc,mean_out_btc,out_and_tx_malicious
count,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07,3.030550e+07
mean,3.097194e-02,-1.441966e-02,9.039420e-04,1.267652e-03,2.388300e-05,1.896389e-03
std,9.266458e-01,7.466096e-01,9.993102e-01,9.981868e-01,1.000810e+00,4.350623e-02
min,-5.199338e+00,-5.199338e+00,-5.199338e+00,-5.199338e+00,-5.199338e+00,0.000000e+00
25%,-4.542490e-01,1.055796e-01,-6.734824e-01,-6.786090e-01,-6.755985e-01,0.000000e+00
50%,-4.542490e-01,1.055796e-01,-2.199233e-03,-1.658429e-03,-2.509140e-03,0.000000e+00
75%,6.425432e-01,1.055796e-01,6.762094e-01,6.747031e-01,6.764628e-01,0.000000e+00
max,5.199338e+00,5.199338e+00,5.199338e+00,5.199338e+00,5.199338e+00,1.000000e+00

In [13]:
# scaled_df.hist(figsize=(20, 20), bins=100, xlabelsize=8, ylabelsize=8, log=False);

In [14]:
# scaled_df.hist(figsize=(20, 20), bins=100, xlabelsize=8, ylabelsize=8, log=True);

In [15]:
norm_scaled_df.to_csv("/Volumes/C/Thesis-2019/cluster-output/transformed_balanced/normalized.csv", index = False, sep=';', encoding='utf-8')

In [16]:
mx_scaled_df.to_csv("/Volumes/C/Thesis-2019/cluster-output/transformed_balanced/min_max.csv", index = False, sep=';', encoding='utf-8')

In [17]:
rb_scaled_df.to_csv("/Volumes/C/Thesis-2019/cluster-output/transformed_balanced/robust.csv", index = False, sep=';', encoding='utf-8')

In [18]:
pw_scaled_df.to_csv("/Volumes/C/Thesis-2019/cluster-output/transformed_balanced/power.csv", index = False, sep=';', encoding='utf-8')

In [19]:
qt_scaled_df.to_csv("/Volumes/C/Thesis-2019/cluster-output/transformed_balanced/quantile_norm.csv", index = False, sep=';', encoding='utf-8')